trigger: 
 branches:
   include:
     - main
 
# schedules:
#   - cron: '34 5 * * *'    
#     displayName: schedule trigeer
#     branches:
#       include:
#         - main   
pool:
  vmImage: 'ubuntu-latest'
  # other options: 'macOS-latest', ' windows-latest

steps:
  # Use a task to install Java 17
- task: JavaToolInstaller@1
  displayName: Install Java
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64' 
    jdkSourceOption: 'PreInstalled'
  # Run Maven build and tests

- task: Maven@4
  displayName: Configuring maven project
  inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21'
      jdkArchitectureOption: 'x64' 
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
- task: CopyFiles@2
  displayName: 'Copy scripts'
  inputs:
      contents: 'scripts/**'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

- publish: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish script'
  artifact: drop